-- Basic
require('core.plugins')
require('core.mappings')
require('core.colors')
require('core.configs')

-- Plugins
require('plugins.neotree')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.cmp')
require('plugins.mason')
require('plugins.telescope')
require('plugins.buffline')
require('plugins.autopairs')
require('plugins.comments')
require('plugins.gitsigns')
require('plugins.lualine')
require('plugins.whichkey')
require('plugins.dashboard')
require('plugins.toggleterm')
require('plugins.nullls')
require('plugins.rusttools')
require('plugins.dap')
require('plugins.surround')
